version: '3'

services:
  speedtest-exporter:
    build: ./speedtest-exporter
    container_name: speedtest-exporter
    ports:
      - "9516:9516"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9091:9090"
    depends_on:
      - speedtest-exporter 
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    restart: unless-stopped
