{
 "title": "Speedtest Dashboard",
 "description": "A dashboard for Prometheus Speedtest Exporter",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current Download Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "internet_download_speed_mbps", "legendFormat": "Download Speed" }
   ]
  },
  {
   "title": "Ping Latency Timeline",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "internet_ping_latency_ms", "legendFormat": "Ping" }
   ]
  },
  {
   "title": "Current Upload Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "internet_upload_speed_mbps", "legendFormat": "Upload Speed" }
   ]
  },
  {
   "title": "Current Ping Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "internet_ping_latency_ms", "legendFormat": "Ping Latency" }
   ]
  },
  {
   "title": "Speedtest Timeline",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "internet_download_speed_mbps", "legendFormat": "Download Speed" },
    { "expr": "internet_upload_speed_mbps", "legendFormat": "Upload Speed" }
   ]
  }
 ]
}